version: "3.9"
services:
  traefik:
    container_name: "traefik"
    image: "traefik"
    restart: always
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/log:/traefik/log
      - ./traefik/FileProvider:/FileProvider
      - ./cert:/cert
    labels:
      - traefik.enable=true

  xray-core:
    container_name: "xray-core"
    image: "teddysun/xray"
    restart: always
    networks:
      - proxy
    volumes:
      - ./xray/trojan:/etc/xray
      - ./cert:/cert

networks:
  proxy:
    external: true
